name: the One sum game
favicon: null
layout_spectrum: 0.9675745123531669
typography_spectrum: 0.12192036584019661
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.442775244358927
  lightness: 0.07354974583722651
  saturation: 0.18078403919935226
  rhythmicContrast: 0.31910219322890043
purpose: []
